complete -c yoo -f
complete -c yoo -n '__fish_use_subcommand' -a init -d 'Create the default config and sample tip pack'
complete -c yoo -n '__fish_use_subcommand' -a config -d 'Print the config file location'
complete -c yoo -n '__fish_use_subcommand' -a doctor -d 'Check tools and project setup'
complete -c yoo -n '__fish_use_subcommand' -a edit -d 'Open the current directory in an editor'
complete -c yoo -n '__fish_use_subcommand' -a fetch -d 'Show environment and project information'
complete -c yoo -n '__fish_use_subcommand' -a status -d 'Alias for fetch'
complete -c yoo -n '__fish_use_subcommand' -a project -d 'Show a structured project overview'
complete -c yoo -n '__fish_use_subcommand' -a session -d 'Start a coding-session timer'
complete -c yoo -n '__fish_use_subcommand' -a tip -d 'Print a random tip'
complete -c yoo -n '__fish_use_subcommand' -a tips -d 'List installed tip packs'
complete -c yoo -n '__fish_use_subcommand' -a completions -d 'Generate shell completions'
complete -c yoo -n '__fish_use_subcommand' -a version -d 'Print version'
complete -c yoo -n '__fish_use_subcommand' -a help -d 'Print help'
complete -c yoo -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish powershell'
complete -c yoo -n '__fish_seen_subcommand_from fetch status project' -l json -d 'Print machine-readable JSON'
complete -c yoo -n '__fish_seen_subcommand_from fetch status project' -l no-art -d 'Hide the ASCII logo'
complete -c yoo -n '__fish_seen_subcommand_from fetch status project' -l plain -d 'Disable ANSI colours'
complete -c yoo -n '__fish_seen_subcommand_from fetch status project' -l theme -xa 'neon ocean mono dracula tokyo-night gruvbox nord rose-pine catppuccin'
complete -c yoo -n '__fish_seen_subcommand_from session' -l minutes -d 'Session length in minutes'
complete -c yoo -n '__fish_seen_subcommand_from edit' -l editor -r -d 'Use a specific editor'
complete -c yoo -n 'not __fish_seen_subcommand_from init config doctor edit fetch status project session tip tips completions version help' -l fast -d 'Skip the typewriter animation'
complete -c yoo -n 'not __fish_seen_subcommand_from init config doctor edit fetch status project session tip tips completions version help' -l no-art -d 'Hide the ASCII logo'
complete -c yoo -n 'not __fish_seen_subcommand_from init config doctor edit fetch status project session tip tips completions version help' -l plain -d 'Disable ANSI colours'
complete -c yoo -n 'not __fish_seen_subcommand_from init config doctor edit fetch status project session tip tips completions version help' -l name -r -d 'Override the profile name'
complete -c yoo -n 'not __fish_seen_subcommand_from init config doctor edit fetch status project session tip tips completions version help' -l theme -xa 'neon ocean mono dracula tokyo-night gruvbox nord rose-pine catppuccin'
complete -c yoo -s h -l help -d 'Print help'
complete -c yoo -s V -l version -d 'Print version'
