#!/usr/bin/env bash
# Render publication files from the exact release archives, never placeholder hashes.
set -euo pipefail
cd "$(dirname "$0")/.."
version=$(scripts/package-version.sh)
assets=$(realpath "${1:?usage: package-metadata.sh ASSET_DIRECTORY [OUTPUT_DIRECTORY]}")
out=${2:-packaging}
linux="yoo-v$version-linux-x86_64.tar.gz"
mac="yoo-v$version-macos-aarch64.tar.gz"
linux_sha=$(sha256sum "$assets/$linux" | cut -d ' ' -f1)
mac_sha=$(sha256sum "$assets/$mac" | cut -d ' ' -f1)
windows="yoo-v$version-windows-x86_64.zip"
windows_sha=$(sha256sum "$assets/$windows" | cut -d ' ' -f1)
mkdir -p "$out/aur" "$out/homebrew"
for item in aur/PKGBUILD homebrew/yoo.rb; do
  sed -e "s/@VERSION@/$version/g" -e "s/@LINUX_SHA@/$linux_sha/g" \
    -e "s/@MAC_SHA@/$mac_sha/g" "packaging/$item.in" > "$out/$item"
done
# The fields below mirror PKGBUILD.in. CI compares this to makepkg --printsrcinfo.
cat > "$out/aur/.SRCINFO" <<SRCINFO
pkgbase = yoo-bin
	pkgdesc = Local CLI for project, Git, and development environment information
	pkgver = $version
	pkgrel = 1
	url = https://github.com/nihitdev/yo-cli
	arch = x86_64
	license = GPL-3.0-or-later
	depends = glibc
	depends = gcc-libs
	optdepends = git: Git repository information
	provides = yoo
	conflicts = yoo
	source = https://github.com/nihitdev/yo-cli/releases/download/v$version/$linux
	sha256sums = $linux_sha

pkgname = yoo-bin
SRCINFO

mkdir -p "$out/winget" "$out/scoop" "$out/chocolatey/tools"
cat > "$out/winget/nihitdev.yoo.yaml" <<WINGET
# Generated by scripts/package-metadata.sh.
PackageIdentifier: Nihitdev.yoo
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
WINGET
cat > "$out/winget/nihitdev.yoo.locale.en-US.yaml" <<WINGET
# Generated by scripts/package-metadata.sh.
PackageIdentifier: Nihitdev.yoo
PackageVersion: $version
PackageLocale: en-US
Publisher: Nihitdev
PublisherUrl: https://github.com/nihitdev
PackageName: yoo
PackageUrl: https://github.com/nihitdev/yo-cli
License: GPL-3.0-or-later
ShortDescription: Local CLI for project, Git, and development environment information
ManifestType: defaultLocale
ManifestVersion: 1.6.0
WINGET
cat > "$out/winget/nihitdev.yoo.installer.yaml" <<WINGET
# Generated by scripts/package-metadata.sh.
PackageIdentifier: Nihitdev.yoo
PackageVersion: $version
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nihitdev/yo-cli/releases/download/v$version/$windows
  InstallerSha256: $windows_sha
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: yoo.exe
ManifestType: installer
ManifestVersion: 1.6.0
WINGET
cat > "$out/scoop/yoo.json" <<SCOOP
{
  "version": "$version",
  "description": "Local CLI for project, Git, and development environment information",
  "homepage": "https://github.com/nihitdev/yo-cli",
  "license": "GPL-3.0-or-later",
  "url": "https://github.com/nihitdev/yo-cli/releases/download/v$version/$windows",
  "hash": "$windows_sha",
  "bin": "yoo.exe",
  "checkver": "github",
  "autoupdate": {
    "url": "https://github.com/nihitdev/yo-cli/releases/download/v\$version/yoo-v\$version-windows-x86_64.zip"
  }
}
SCOOP

cat > "$out/chocolatey/yoo.nuspec" <<NUSPEC
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>yoo</id>
    <version>$version</version>
    <title>yoo</title>
    <authors>Nihit</authors>
    <owners>nihitdev</owners>
    <projectUrl>https://github.com/nihitdev/yo-cli</projectUrl>
    <licenseUrl>https://github.com/nihitdev/yo-cli/blob/main/LICENSE</licenseUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Local CLI for project, Git, and development environment information.</description>
    <tags>cli developer git rust</tags>
  </metadata>
</package>
NUSPEC
cat > "$out/chocolatey/tools/chocolateyinstall.ps1" <<CHOCOLATEY
\$ErrorActionPreference = 'Stop'
\$toolsDir = \$(Split-Path -parent \$MyInvocation.MyCommand.Definition)
\$url = 'https://github.com/nihitdev/yo-cli/releases/download/v$version/yoo-windows-x86_64.exe'
Get-ChocolateyWebFile -PackageName 'yoo' -FileFullPath (Join-Path \$toolsDir 'yoo.exe') -Url \$url -Checksum '$windows_sha' -ChecksumType 'sha256'
Install-BinFile -Name 'yoo' -Path (Join-Path \$toolsDir 'yoo.exe')
CHOCOLATEY

source_archive=$(mktemp)
trap 'rm -f "$source_archive"' EXIT
if curl --fail --location --retry 3 --silent --show-error \
  "https://github.com/nihitdev/yo-cli/archive/refs/tags/v$version.tar.gz" \
  --output "$source_archive"; then
  mkdir -p "$out/void"
  source_sha512=$(sha512sum "$source_archive" | cut -d ' ' -f1)
  sed -e "s/@VERSION@/$version/g" -e "s/@SOURCE_SHA512@/$source_sha512/g" \
    packaging/void/template.in > "$out/void/template"
elif [[ "${GITHUB_REF_TYPE:-}" == tag ]]; then
  echo "Unable to download source archive for release tag v$version" >&2
  exit 1
else
  echo "Void template skipped: v$version is not tagged yet" >&2
fi
